using System;
using SQLite;

namespace Facile.Models
{
	[Table("ditt2016")]
	public class Ditte
	{
		[PrimaryKey , AutoIncrement]
		public int dit_codice { get; set; }

		public string dit_rag_soc1 { get; set; }
		public string dit_rag_soc2 { get; set; }
		public string dit_desc { get; set; }
		public string dit_pers { get; set; }
		public string dit_sesso { get; set; }
		public string dit_indirizzo { get; set; }
		public string dit_citta { get; set; }
		public string dit_cap { get; set; }
		public string dit_prov { get; set; }
		public string dit_codfis { get; set; }
		public string dit_piva { get; set; }
		public string dit_tel { get; set; }
		public string dit_cel { get; set; }
		public string dit_fax { get; set; }
		public string dit_naz { get; set; }
		public string dit_cod_att { get; set; }
		public string dit_des_att { get; set; }
		public string dit_natura { get; set; }
		public string dit_cod_regime { get; set; }
		public string dit_des_regime { get; set; }
		public int dit_anno { get; set; }
		public int dit_mas_cli { get; set; }
		public int dit_mas_for { get; set; }
		public string dit_moneta { get; set; }
		public int dit_dec { get; set; }
		public string dit_dec_str { get; set; }
		public string dit_free_space { get; set; }
		public int dit_gior_pag { get; set; }
		public int dit_gior_row { get; set; }
		public DateTime? dit_data_0 { get; set; }
		public DateTime? dit_data_1 { get; set; }
		public DateTime? dit_data_2 { get; set; }
		public DateTime? dit_data_3 { get; set; }
		public DateTime? dit_data_4 { get; set; }
		public DateTime? dit_data_5 { get; set; }
		public DateTime? dit_data_6 { get; set; }
		public int dit_mas_0 { get; set; }
		public int dit_mas_1 { get; set; }
		public int dit_con_0 { get; set; }
		public int dit_con_1 { get; set; }
		public int dit_sot_0 { get; set; }
		public int dit_sot_1 { get; set; }
		public double dit_tot_per_0 { get; set; }
		public double dit_tot_per_1 { get; set; }
		public double dit_tot_anno_0 { get; set; }
		public double dit_tot_anno_1 { get; set; }
		public double dit_rib_imp_0 { get; set; }
		public double dit_rib_imp_1 { get; set; }
		public double dit_rib_imp_2 { get; set; }
		public double dit_rib_imp_3 { get; set; }
		public double dit_rib_imp_4 { get; set; }
		public double dit_rib_bolli_0 { get; set; }
		public double dit_rib_bolli_1 { get; set; }
		public double dit_rib_bolli_2 { get; set; }
		public double dit_rib_bolli_3 { get; set; }
		public double dit_rib_bolli_4 { get; set; }
		public int dit_rib_cod_iva { get; set; }
		public int dit_rib_cod_ban { get; set; }
		public string dit_rib_sia { get; set; }
		public double dit_rib_spese { get; set; }
		public double dit_rib_vers { get; set; }
		public double dit_trat_imp_0 { get; set; }
		public double dit_trat_imp_1 { get; set; }
		public double dit_trat_imp_2 { get; set; }
		public double dit_trat_imp_3 { get; set; }
		public double dit_trat_imp_4 { get; set; }
		public double dit_trat_bolli_0 { get; set; }
		public double dit_trat_bolli_1 { get; set; }
		public double dit_trat_bolli_2 { get; set; }
		public double dit_trat_bolli_3 { get; set; }
		public double dit_trat_bolli_4 { get; set; }
		public int dit_trat_cod_iva { get; set; }
		public double dit_trat_perc_bolli { get; set; }
		public double dit_trat_spese { get; set; }
		public int dit_dep_attivo { get; set; }
		public int dit_cod_iva { get; set; }
		public int dit_cod_mis { get; set; }
		public int dit_iva_inc { get; set; }
		public int dit_bol_mod { get; set; }
		public int dit_fat_mod { get; set; }
		public int dit_ddt_mod { get; set; }
		public int dit_ddt_int { get; set; }
		public int dit_fat_int { get; set; }
		public int dit_con_vendite { get; set; }
		public int dit_con_pagam { get; set; }
		public int dit_mag_vendite { get; set; }
		public int dit_mag_acquisti { get; set; }
		public int dit_mag_resi { get; set; }
		public string dit_reg_fat { get; set; }
		public string dit_reg_ddt { get; set; }
		public string dit_reg_bol { get; set; }
		public int dit_con_effetti { get; set; }
		public int dit_con_inc { get; set; }
		public int dit_denso { get; set; }
		public int dit_mw25 { get; set; }
		public double dit_gior_dare { get; set; }
		public double dit_gior_avere { get; set; }
		public int dit_buo_mod { get; set; }
		public int dit_buo_int { get; set; }
		public string dit_reg_buo { get; set; }
		public string dit_port_barcode { get; set; }
		public string dit_port_modem { get; set; }
		public string dit_port_cassa { get; set; }
		public string dit_cassa { get; set; }
		public int dit_cheek_piva { get; set; }
		public string dit_articolo { get; set; }
		public string dit_bartype { get; set; }
		public int dit_conferma { get; set; }
		public int dit_acc_mod { get; set; }
		public int dit_acc_int { get; set; }
		public string dit_reg_acc { get; set; }
		public int dit_listino { get; set; }
		public int dit_scocar { get; set; }
		public int dit_scoart { get; set; }
		public int dit_ean { get; set; }
		public int dit_ean_naz { get; set; }
		public int dit_ean_pro { get; set; }
		public int dit_windows_unused { get; set; }
		public int dit_ask_list { get; set; }
		public int dit_mag_ven_no { get; set; }
		public int dit_mag_acq_no { get; set; }
		public int dit_mag_ord_cli { get; set; }
		public int dit_mag_ord_for { get; set; }
		public int dit_cod_iva_sco { get; set; }
		public int dit_alert { get; set; }
		public int dit_mag_rim { get; set; }
		public int dit_mas_ricavi { get; set; }
		public int dit_con_ricavi { get; set; }
		public int dit_con_ricevute { get; set; }
		public int dit_qta_zero { get; set; }
		public int dit_sot_ricavi { get; set; }
		public string dit_reg_ric { get; set; }
		public string dit_reg_ord { get; set; }
		public string dit_reg_pre { get; set; }
		public string dit_reg_ofo { get; set; }
		public int dit_ric_mod { get; set; }
		public int dit_ord_mod { get; set; }
		public int dit_pre_mod { get; set; }
		public int dit_ofo_mod { get; set; }
		public double dit_fat_spese { get; set; }
		public int dit_con_autofat { get; set; }
		public int dit_versione { get; set; }
		public int dit_build { get; set; }
		public int dit_reg_unico { get; set; }
		public int dit_dos_fat { get; set; }
		public int dit_dos_acc { get; set; }
		public int dit_dos_ddt { get; set; }
		public int dit_dos_buo { get; set; }
		public int dit_dos_bol { get; set; }
		public int dit_dos_ric { get; set; }
		public int dit_dos_ord { get; set; }
		public int dit_dos_ofo { get; set; }
		public int dit_dos_pre { get; set; }
		public int dit_dos_auf { get; set; }
		public string dit_reg_auf { get; set; }
		public int dit_auf_mod { get; set; }
		public string dit_drive_cpy { get; set; }
		public int dit_mag_let { get; set; }
		public int dit_con_vsd { get; set; }
		public int dit_usawin { get; set; }
		public double dit_commis { get; set; }
		public int dit_medkil { get; set; }
		public int dit_progres { get; set; }
		public int dit_skip_eti { get; set; }
		public int dit_fro_mod { get; set; }
		public int dit_nopreview { get; set; }
		public short dit_copie { get; set; }
		public int dit_mas_ban { get; set; }
		public int dit_con_ban { get; set; }
		public int dit_con_inv { get; set; }
		public int dit_con_ins { get; set; }
		public int dit_con_res { get; set; }
		public int dit_cau_carpro { get; set; }
		public int dit_cau_scapro { get; set; }
		public int dit_cau_sfipro { get; set; }
		public int dit_con_pagam_ban { get; set; }
		public int dit_con_inc_ban { get; set; }
		public int dit_con_iva { get; set; }
		public int dit_con_ret_for { get; set; }
		public int dit_con_ret_cli { get; set; }
		public int dit_con_iva_ban { get; set; }
		public int dit_con_cre { get; set; }
		public int dit_mas_cassa { get; set; }
		public int dit_con_cassa { get; set; }
		public DateTime? dit_zuc_data { get; set; }
		public int dit_zuc_pag { get; set; }
		public int dit_zuc_row { get; set; }
		public double dit_zuc_carico { get; set; }
		public double dit_zuc_scarico { get; set; }
		public int dit_cod_iva_ese { get; set; }
		public int dit_rif_buoni { get; set; }
		public int dit_riporto_sche { get; set; }
		public int dit_rag_dest { get; set; }
		public int dit_maxrowcar { get; set; }
		public double dit_spetra { get; set; }
		public double dit_spetra_perc_unused { get; set; }
		public int dit_mod_riba { get; set; }
		public int dit_prev_codice { get; set; }
		public int dit_ventilazione { get; set; }
		public DateTime? dit_mov_serial_data { get; set; }
		public int dit_img { get; set; }
		public string dit_sotcli { get; set; }
		public string dit_sotfor { get; set; }
		public int dit_aggancio { get; set; }
		public short dit_listino_tra { get; set; }
		public int dit_mov_serial_file { get; set; }
		public int dit_marchio { get; set; }
		public int dit_obbligo_rep { get; set; }
		public int dit_uti_mas { get; set; }
		public int dit_uti_con { get; set; }
		public int dit_uti_sot { get; set; }
		public int dit_per_mas { get; set; }
		public int dit_per_con { get; set; }
		public int dit_per_sot { get; set; }
		public int dit_bil_mas { get; set; }
		public int dit_bil_con { get; set; }
		public int dit_bil_sot { get; set; }
		public int dit_pro_mas { get; set; }
		public int dit_pro_con { get; set; }
		public int dit_pro_sot { get; set; }
		public int dit_chi_cau { get; set; }
		public int dit_ini_mas { get; set; }
		public int dit_ini_con { get; set; }
		public int dit_ini_sot { get; set; }
		public int dit_fin_mas { get; set; }
		public int dit_fin_con { get; set; }
		public int dit_fin_sot { get; set; }
		public int dit_ape_mas { get; set; }
		public int dit_ape_con { get; set; }
		public int dit_ape_sot { get; set; }
		public int dit_ape_cau { get; set; }
		public int dit_cau_tradep { get; set; }
		public int dit_tresconti_unused { get; set; }
		public double dit_quotazione { get; set; }
		public string dit_cciaa { get; set; }
		public string dit_tribunale { get; set; }
		public short dit_ta1 { get; set; }
		public short dit_ta2 { get; set; }
		public short dit_ta3 { get; set; }
		public int dit_disableass { get; set; }
		public int dit_con_resi { get; set; }
		public int dit_mas_abb_att { get; set; }
		public int dit_con_abb_att { get; set; }
		public int dit_sot_abb_att { get; set; }
		public int dit_mas_abb_pas { get; set; }
		public int dit_con_abb_pas { get; set; }
		public int dit_sot_abb_pas { get; set; }
		public int dit_check_sca { get; set; }
		public int dit_con_rin { get; set; }
		public int dit_cli_stt { get; set; }
		public int dit_for_gru { get; set; }
		public int dit_for_stt { get; set; }
		public string dit_coc1 { get; set; }
		public string dit_coc2 { get; set; }
		public string dit_coc3 { get; set; }
		public string dit_coc4 { get; set; }
		public string dit_coc5 { get; set; }
		public string dit_cof1 { get; set; }
		public string dit_cof2 { get; set; }
		public string dit_cof3 { get; set; }
		public string dit_cof4 { get; set; }
		public string dit_cof5 { get; set; }
		public double dit_spetra_imp_0 { get; set; }
		public double dit_spetra_imp_1 { get; set; }
		public double dit_spetra_imp_2 { get; set; }
		public double dit_spetra_imp_3 { get; set; }
		public double dit_spetra_imp_4 { get; set; }
		public double dit_spetra_per_0 { get; set; }
		public double dit_spetra_per_1 { get; set; }
		public double dit_spetra_per_2 { get; set; }
		public double dit_spetra_per_3 { get; set; }
		public double dit_spetra_per_4 { get; set; }
		public int dit_cod_age { get; set; }
		public int dit_sblocca_cont { get; set; }
		public int dit_list_par { get; set; }
		public int dit_eseconpiu { get; set; }
		public int dit_sqldata { get; set; }
		public int dit_fisc_car { get; set; }
		public int dit_fisc_sca { get; set; }
		public string dit_smartkey { get; set; }
		public int dit_pin_0 { get; set; }
		public int dit_pin_1 { get; set; }
		public int dit_pin_2 { get; set; }
		public string dit_ftp_server { get; set; }
		public bool dit_ftp_use { get; set; }
		public bool dit_filtra { get; set; }
		public int dit_cau_rif { get; set; }
		public bool dit_expcli { get; set; }
		public bool dit_filtra_sca { get; set; }
		public bool dit_autosync { get; set; }
		public bool dit_solobarcode { get; set; }
		public short dit_bollini_0 { get; set; }
		public short dit_bollini_1 { get; set; }
		public short dit_bollini_2 { get; set; }
		public short dit_bollini_3 { get; set; }
		public short dit_bollini_4 { get; set; }
		public short dit_bollini_5 { get; set; }
		public short dit_bollini_6 { get; set; }
		public double dit_bollini_soglia { get; set; }
		public double dit_bollini_premio1 { get; set; }
		public int dit_bollini_min { get; set; }
		public double dit_interessi_mora { get; set; }
		public bool dit_filtradep { get; set; }
		public string dit_reg_sco { get; set; }
		public int dit_cli_start { get; set; }
		public int dit_cli_stop { get; set; }
		public int dit_for_start { get; set; }
		public int dit_for_stop { get; set; }
		public short dit_posid { get; set; }
		public short dit_livello_imp { get; set; }
		public string dit_prefisso_tes { get; set; }
		public bool dit_usa_operatori { get; set; }
		public bool dit_ftp_passive { get; set; }
		public bool dit_forcesql { get; set; }
		public int dit_eti_mod { get; set; }
		public int dit_mag_ini { get; set; }
		public bool dit_usa_lotti { get; set; }
		public bool dit_usa_coefmol { get; set; }
		public string dit_reg_car { get; set; }
		public bool dit_blocca_prezzi { get; set; }
		public int dit_reparto_cassa { get; set; }
		public bool dit_cod_seriale { get; set; }
		public bool dit_blocco_ope { get; set; }
		public int dit_con_acquisti { get; set; }
		public bool dit_alimentari { get; set; }
		public bool dit_bloccoscaduti { get; set; }
		public bool dit_visualizzasaldi { get; set; }
		public int dit_mas_anticipi { get; set; }
		public int dit_con_anticipi { get; set; }
		public int dit_sot_anticipi { get; set; }
		public bool dit_autocont { get; set; }
		public bool dit_mov_fpf { get; set; }
		public string dit_reg_fpf { get; set; }
		public string dit_ftp_pwd { get; set; }
		public string dit_ftp_user { get; set; }
		public string dit_cognome { get; set; }
		public string dit_nome { get; set; }
		public DateTime? dit_data_nas { get; set; }
		public string dit_citta_nas { get; set; }
		public string dit_cap_nas { get; set; }
		public string dit_prov_nas { get; set; }
		public string dit_codfis_tit { get; set; }
		public string dit_citta_res { get; set; }
		public string dit_indirizzo_res { get; set; }
		public string dit_cap_res { get; set; }
		public string dit_prov_res { get; set; }
		public int dit_mod_com_cas { get; set; }
		public int dit_mod_com_bar { get; set; }
		public int dit_mod_com_cuc { get; set; }
		public int dit_mod_com_piz { get; set; }
		public bool dit_abilita_tabacchi { get; set; }
		public string dit_dep_fiscale { get; set; }
		public string dit_com_rivendita { get; set; }
		public short dit_num_rivendita { get; set; }
		public int dit_mod_com_pas { get; set; }
		public int dit_mod_com_op1 { get; set; }
		public int dit_mod_com_op2 { get; set; }
		public int dit_mod_com_op3 { get; set; }
		public int dit_mod_com_op4 { get; set; }
		public int dit_mod_com_op5 { get; set; }
		public int dit_tipo_com_cas_unused { get; set; }
		public int dit_tipo_com_bar_unused { get; set; }
		public int dit_tipo_com_cuc_unused { get; set; }
		public int dit_tipo_com_piz_unused { get; set; }
		public int dit_tipo_com_pas_unused { get; set; }
		public int dit_tipo_com_op1_unused { get; set; }
		public int dit_tipo_com_op2_unused { get; set; }
		public int dit_tipo_com_op3_unused { get; set; }
		public int dit_tipo_com_op4_unused { get; set; }
		public int dit_tipo_com_op5_unused { get; set; }
		public int dit_mag_car_pal { get; set; }
		public int dit_tra_pre { get; set; }
		public int dit_tra_car_pal { get; set; }
		public int dit_tra_rim { get; set; }
		public string dit_citta_dom { get; set; }
		public string dit_indirizzo_dom { get; set; }
		public string dit_cap_dom { get; set; }
		public string dit_prov_dom { get; set; }
		public double dit_capitale_soc { get; set; }
		public double dit_bolli { get; set; }
		public bool dit_nocalc_sostituzioni { get; set; }
		public double dit_fido { get; set; }
		public bool dit_un_info_riv_used { get; set; }
		public string dit_reg_oro { get; set; }
		public bool dit_calc_colli { get; set; }
		public bool dit_automaticprice { get; set; }
		public bool dit_esporta { get; set; }
		public bool dit_send { get; set; }
		public short dit_listino_risto { get; set; }
		public int dit_fpf_mod { get; set; }
		public int dit_dos_fpf { get; set; }
		public bool dit_abilita_das_unused { get; set; }
		public short dit_aggiorna_listino { get; set; }
		public bool dit_gest_seriali { get; set; }
		public bool dit_comande_clear { get; set; }
		public int dit_iva_cli { get; set; }
		public int dit_iva_age { get; set; }
		public int dit_cod_ban { get; set; }
		public short dit_stelle { get; set; }
		public int dit_mod_voucher { get; set; }
		public int dit_mod_estratto { get; set; }
		public int dit_mod_sche { get; set; }
		public int dit_mod_istat { get; set; }
		public int dit_start_istat { get; set; }
		public bool dit_dis_ps { get; set; }
		public bool dit_disrag_istat { get; set; }
		public bool dit_numps_gen { get; set; }
		public bool dit_fat_netto_unused { get; set; }
		public bool dit_emis { get; set; }
		public bool dit_stmodulo { get; set; }
		public bool dit_stdati { get; set; }
		public int dit_isola_age { get; set; }
		public int dit_settore { get; set; }
		public string dit_cod_trh { get; set; }
		public string dit_cod_lho { get; set; }
		public string dit_cod_stg { get; set; }
		public string dit_specie { get; set; }
		public bool dit_no_scorporo { get; set; }
		public bool dit_sco_iva_esc { get; set; }
		public int dit_dos_prc { get; set; }
		public int dit_prc_mod { get; set; }
		public int dit_sol_mod { get; set; }
		public int dit_con_cash { get; set; }
		public short dit_codtagcol { get; set; }
		public int dit_con_corr { get; set; }
		public int dit_con_cnp { get; set; }
		public int dit_con_incric { get; set; }
		public bool dit_ric_prezzo { get; set; }
		public int dit_fat_cnp { get; set; }
		public short dit_codbil { get; set; }
		public int dit_last_cash_fat { get; set; }
		public bool dit_ivasuproforma { get; set; }
		public int dit_last_scontrino { get; set; }
		public string dit_smtp_server { get; set; }
		public string dit_smtp_notify { get; set; }
		public string dit_sms_server { get; set; }
		public string dit_sms_sender { get; set; }
		public string dit_smtp_replyto { get; set; }
		public short dit_usasmart { get; set; }
		public string dit_user { get; set; }
		public DateTime? dit_last_update { get; set; }
		public int dit_mer_premi { get; set; }
		public bool dit_applica_iva_sommin { get; set; }
		public bool dit_prel_prev { get; set; }
		public bool dit_no_add_auto { get; set; }
		public string dit_cod_struttura { get; set; }
		public short dit_mod_istat_telematico { get; set; }
		public bool dit_preconto_palmare { get; set; }
		public bool dit_scontrino_palmare { get; set; }
		public short dit_sms_provider { get; set; }
		public short dit_sms_gateway { get; set; }
		public string dit_sms_password { get; set; }
		public bool dit_no_auto_keyboard { get; set; }
		public string dit_cod_cli_logista { get; set; }
		public bool dit_ftp_log { get; set; }
		public string dit_smtp_pwd { get; set; }
		public string dit_smtp_user { get; set; }
		public bool dit_smtp_log { get; set; }
		public int dit_tra_con_ban { get; set; }
		public int dit_tra_rit_ban { get; set; }
		public int dit_tra_rot_ban { get; set; }
		public int dit_tra_rip_ban { get; set; }
		public int dit_mas_bolli { get; set; }
		public int dit_con_bolli { get; set; }
		public int dit_sot_bolli { get; set; }
		public int dit_mas_spese { get; set; }
		public int dit_con_spese { get; set; }
		public int dit_sot_spese { get; set; }
		public int dit_mas_abbuoni { get; set; }
		public int dit_con_abbuoni { get; set; }
		public int dit_sot_abbuoni { get; set; }
		public int dit_mas_acconti { get; set; }
		public int dit_con_acconti { get; set; }
		public int dit_sot_acconti { get; set; }
		public int dit_mas_omaggi { get; set; }
		public int dit_con_omaggi { get; set; }
		public int dit_sot_omaggi { get; set; }
		public bool dit_forza_agente { get; set; }
		public short dit_bizerba_file { get; set; }
		public short dit_bizerba_formato { get; set; }
		public string dit_ecom_server { get; set; }
		public string dit_ecom_user { get; set; }
		public string dit_ecom_pwd { get; set; }
		public string dit_ecom_docs_path { get; set; }
		public short dit_ecom_ssh_port { get; set; }
		public string dit_ecom_api_token_old { get; set; }
		public int dit_eti_promo_piccola_unused { get; set; }
		public int dit_eti_promo_media_unused { get; set; }
		public int dit_eti_promo_grande_unused { get; set; }
		public int dit_mas_ritenuta { get; set; }
		public int dit_con_ritenuta { get; set; }
		public int dit_sot_ritenuta { get; set; }
		public int dit_bci_mod { get; set; }
		public int dit_mod_preconto { get; set; }
		public double dit_magg_servizio { get; set; }
		public bool dit_no_obbligo_partita { get; set; }
		public bool dit_hide_checkout { get; set; }
		public bool dit_conto_rag_reparti { get; set; }
		public int dit_gen_cod_start { get; set; }
		public int dit_gen_cod_stop { get; set; }
		public bool dit_blocca_trasf_art { get; set; }
		public bool dit_dati_essenz_mov { get; set; }
		public bool dit_hide_costo_med_k { get; set; }
		public bool dit_disable_fidelity_k { get; set; }
		public int dit_eti_uni_logistica { get; set; }
		public int dit_smtp_port { get; set; }
		public bool dit_smtp_usa_ssl { get; set; }
		public string dit_pbx_server { get; set; }
		public int dit_pbx_port { get; set; }
		public bool dit_disable_exp_counter { get; set; }
		public bool dit_web_mar { get; set; }
		public bool dit_web_mer { get; set; }
		public bool dit_web_rep { get; set; }
		public bool dit_web_set { get; set; }
		public int dit_web_dep { get; set; }
		public int dit_web_lis { get; set; }
		public bool dit_web_usa_sco { get; set; }
		public int dit_web_img_size { get; set; }
		public bool dit_inv_killin { get; set; }
		public int dit_iva_spese { get; set; }
		public DateTime? dit_impo_sog_start { get; set; }
		public DateTime? dit_impo_sog_stop { get; set; }
		public int dit_impo_sog_days { get; set; }
		public string dit_ecom_api_token { get; set; }
		public short dit_suffisso_doc { get; set; }
		public bool dit_iva_cassa { get; set; }
		public DateTime? dit_iva_cassa_start { get; set; }
		public DateTime? dit_iva_cassa_stop { get; set; }
		public bool dit_store_latlong { get; set; }
		public int dit_eti_uni_commerciale { get; set; }
		public int dit_sscc_serial { get; set; }
		public short dit_sscc_extension { get; set; }
		public short dit_bollini_compleanno_num { get; set; }
		public short dit_bollini_compleanno_ope { get; set; }
		public bool dit_calc_colli_auto_pos { get; set; }
		public bool dit_blank { get; set; }
		public short dit_regime_fiscale { get; set; }
		public string dit_prov_uri { get; set; }
		public string dit_num_rea { get; set; }
		public bool dit_socio_unico { get; set; }
		public bool dit_in_liquidazione { get; set; }
		public int dit_prog_invio_fat_el { get; set; }
		public string dit_bollo_virtuale { get; set; }
		public string dit_cau_pag_rit_acc { get; set; }
		public string dit_tipo_cassa_prev { get; set; }
		public bool dit_skip_rif_ord_cli { get; set; }
		public bool dit_no_rep_e_mar_ven_doc { get; set; }
		public string dit_reg_fat_pa { get; set; }
		public int dit_cac_fat_pa { get; set; }
		public int dit_cod_cli_fat_pa { get; set; }
		public string dit_nota_split_payment { get; set; }
		public string dit_reg_cre_pa { get; set; }
		public int dit_cac_cre_pa { get; set; }
		public bool dit_ditta_individuale { get; set; }
		public bool dit_provvigione_scontrini { get; set; }
		public int dit_sez_pro_forma { get; set; }
		public bool dit_non_iscritta_rea { get; set; }
		public bool dit_show_web_mask { get; set; }
		public bool dit_buoni_sconto_enable { get; set; }
		public short dit_buoni_sconto_org { get; set; }
		public short dit_buoni_sconto_dep { get; set; }
		public int dit_buoni_sconto_last { get; set; }
		public bool dit_buoni_sconto_circ { get; set; }
		public double dit_buoni_sconto_soglia { get; set; }
		public double dit_buoni_sconto_val_1 { get; set; }
		public double dit_buoni_sconto_val_2 { get; set; }
		public double dit_buoni_sconto_val_3 { get; set; }
		public double dit_buoni_sconto_val_altri { get; set; }
		public short dit_buoni_sconto_mul_0 { get; set; }
		public short dit_buoni_sconto_mul_1 { get; set; }
		public short dit_buoni_sconto_mul_2 { get; set; }
		public short dit_buoni_sconto_mul_3 { get; set; }
		public short dit_buoni_sconto_mul_4 { get; set; }
		public short dit_buoni_sconto_mul_5 { get; set; }
		public short dit_buoni_sconto_mul_6 { get; set; }
		public int dit_buoni_sconto_validita { get; set; }
		public int dit_buoni_sconto_durata { get; set; }
		public int dit_buoni_sconto_formato { get; set; }
		public short dit_gen_cod_format { get; set; }
		public short dit_gen_cod_cifre { get; set; }
		public string dit_gen_cod_prefix { get; set; }
		public string dit_gen_cod_suffix { get; set; }
		public int dit_cau_imppro { get; set; }
		public int dit_cau_inipro { get; set; }
		public string dit_web_registro { get; set; }
		public int dit_web_cli_eco { get; set; }
		public bool dit_blocca_ric_doc_lav { get; set; }
		public bool dit_ord_frazionabili { get; set; }
		public bool dit_ofo_frazionabili { get; set; }
		public bool dit_sco_parlante { get; set; }
		public short dit_num_ecr { get; set; }
		public string dit_smtp_report { get; set; }
		public int dit_liq_iva_per_counter { get; set; }
		public int dit_fatture_xml_counter { get; set; }
		public string dit_naz_dom { get; set; }
		public bool dit_web_sta { get; set; }
		public bool dit_isam_browsing { get; set; }
		public int dit_geri_exp_counter { get; set; }
		public bool calc_prezzi_per_qta { get; set; }
	}
}
